### ISSUE TITLE
Incompatability with YARIP

### ISSUE THREAD

**Issue by Link-Satonaka** [sblask/firefox-image-forward#5]
The keybinding to "end iteration mode" doesn't actually work. You have it documented as Ctrl-Shift-B, however Ctrl-Shift-anykey will end the iteration mode, in addition to swallowing any Ctrl-Shift shortcut for the rest of the firefox session.

For example, if I have used imageforward, I would need to restart firefox to access addons via Ctrl-Shift-a

**Comment by sblask** [comment]
It works for me. You wrote somewhere that it's related to a different addon, didn't you?

**Comment by Link-Satonaka** [comment]
I've isolated the conflicting extension.

https://addons.mozilla.org/en-US/firefox/addon/yarip/

**Comment by sblask** [comment]
As nothing happened in the other issues, I am closing this for now.
